### ISSUE TITLE
Lua Errors on start

### ISSUE THREAD

**Issue by CawsForConcern** [TheRealHypo/MobInfo2#1]
Pastebin link: https://pastebin.com/Gq56gHYF

7 lua errors show up on launching and loading the addon. I've tried deleting my WTF and cache folders already.

Not running any other addons.

**Comment by CawsForConcern** [comment]
Figured out the issue: The Libs folder from MobInfo2 is missing.
Made a pull request to fix here: #2

**Comment by ghost** [comment]
New version should fix the issue :)
