### ISSUE TITLE
Holding ALT for tooltip info needs it to be re-mouseovered. Not a problem if you add boss filter for loot.

### ISSUE THREAD

**Issue by karyzan** [TheRealHypo/MobInfo2#18]

**Comment by ghost** [comment]
Can you please explain what you mean by the Boss Filter ? 

I didn't had the Problem with the ALT press currently, why did you activate it in the firstplace ? If the Tooltip itself bothered you, one of the updated today made the Tooltip clickthrough.

**Comment by ghost** [comment]
Found a solution for this problem. Will include it in a future update.

**Comment by karyzan** [comment]
> Found a solution for this problem. Will include it in a future update.

Thanks a lot mate. What I mean by boss filter is that the item drops doesn't show on raid bosses. Or even better, option for turning off item drops in combat would solve the whole thing. Thanks for you work!

**Comment by ghost** [comment]
But with Item Drops you still mean, only the part of the Tooltip that shows the Items, right ? :)
