### ISSUE TITLE
Cloth/skin

### ISSUE THREAD

**Issue by ZeeQuill** [TheRealHypo/MobInfo2#3]
Cloth and skinning item drop tracking doesn't work.

**Comment by ZeeQuill** [comment]
as an update... this ONLY works if you skin things that someone else killed..... not things you killed

**Comment by ghost** [comment]
Cloth drops do work for me, pretty good actually. 
Skinning, I might have to look into, didn't skin in classic yet

**Comment by kernighan** [comment]
Skinning has been working fine for me as best I can tell, but I'll pay closer attention.

**Comment by ghost** [comment]
Any updates here ? 

I still don't have a skinning char, so I couldn't look further into it.

**Comment by kernighan** [comment]
It appears to be working fine to me, but I haven't payed super close attention.  I'll see if I can get a better confirmation next time I'm skinning in a new area.

**Comment by ZeeQuill** [comment]
Classic is what I'm talking about. Skinning doesn't work most the time.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by ghost** [comment]
Fixed with PR #17
