### ISSUE TITLE
Lacks proper versioning

### ISSUE THREAD

**Issue by kernighan** [TheRealHypo/MobInfo2#4]
Please properly version the mod so that when you do new releases it has a unique version number as part of the zip file (assuming you set up autopackaging on tagged commits with github).

**Comment by ghost** [comment]
Well, I went with the classic patch version to identify. But since there have been many releases now I'll think about a proper versioning

**Comment by ghost** [comment]
New Versioning will now be <InterfaceVersion>.<Addon Version> ... I have not setup autopackaging so far.

**Comment by kernighan** [comment]
Thanks!  The auto packaging is extremely helpful.  There's a guide I can point you at if you need.

**Comment by ghost** [comment]
Would be helpful :)

**Comment by kernighan** [comment]
https://authors.curseforge.com/knowledge-base/projects/3451-automatic-packaging

**Comment by ghost** [comment]
Just released the first version with Auto Packaging :)

**Comment by ghost** [comment]
@kernighan Any idea how I could avoid having the changelog getting pushed into the file on curseforge ? it includes my email address which I do not really like to have on curseforge. The extra click to Github should happen :D

**Comment by kernighan** [comment]
I use an email specifically for WoW to mask my real life name, and then add it to my .git/config so every commit uses it:

```
~/git/wow/addon$ cat .git/config
......
[user]
        name = "Yunohu"
        email = "kernighan@gmail.com"
```
