### ISSUE TITLE
XP granted for NPC tracked with wrong level NPC

### ISSUE THREAD

**Issue by kernighan** [TheRealHypo/MobInfo2#5]
I've noticed an interesting and odd issue when fighting NPCs with the same name but different levels.  Invariably, the amount of XP given for an NPC of level X is tracked in mobinfo2 with the NPC of level Y, and vice versa.  For example, I was fighting boars in Westfall.  The XP granted by a level 15 boar was indicated in the tooltip of the level 14 boar (along with the number of kills to level), while the XP granted by a level 14 boar was tracked with the level 15 boar tooltips.

I've seen this consistently with multiple NPCs across various zones.

**Comment by ghost** [comment]
Interesting case, I'll have to check that out when I have some time. Could be something wrong with the recording of the mob data. But It could also be that the WoW API does report it wrongly for AoE Kills e.g

**Comment by ghost** [comment]
It could have been related to another Issue where when Combined Mobdata was active, sometimes the combined mobdata got saved. Which resulted in wrong values on the same type of mob.

Do you have Combined Mobs active ?

**Comment by kernighan** [comment]
I did at the time I filed this.  I since disabled it and reset my database, and haven't noticed it again.

**Comment by kernighan** [comment]
Just to note, was not doing AoE kills either.

**Comment by ghost** [comment]
Okay so I guess this will be fixed to after the changes in the new branch.
