### ISSUE TITLE
Feature request - Register the icon with Titan Panel

### ISSUE THREAD

**Issue by Scoboose** [TheRealHypo/MobInfo2#6]
I like to try and keep as many buttons off my minimap as possible. Many plugins allow placement of there map icon on titan panel. I would love if this was the case for mobinfo2-classic.

Thank you,
-Scoboose

**Comment by Scoboose** [comment]
I have made the necessary changes and created a pull request to add this functionality.
#8

**Comment by ghost** [comment]
Hey Great Job ! :)
