### ISSUE TITLE
Feature request - Click threw tooltip

### ISSUE THREAD

**Issue by Scoboose** [TheRealHypo/MobInfo2#7]
I find myself having to reposition the camera some times to be able to click a mob. It would be great if the tooltip was click threw.

Thank you,
-Scoboose

**Comment by ghost** [comment]
Hey Scoboose, Will have to look into some more guides to see how to do that, but that definitly bugs me out too 👍

**Comment by Scoboose** [comment]
I have added this functionality in pull request #15

**Comment by ghost** [comment]
Thanks a lot Scoboose !
