### ISSUE TITLE
LUA error just to let you know. (Swatter)

### ISSUE THREAD

**Issue by MatizzX** [TheRealHypo/MobInfo2#9]
Date: 2019-09-13 15:17:49
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\MobInfo2\MI2_Tooltip.lua line 489:
   attempt to concatenate local 'name' (a nil value)
Debug:
   MobInfo2\MI2_Tooltip.lua:489: MI2_CreateTooltip()
   MobInfo2\MI2_Tooltip.lua:255: MI2_TooltipMouseoverUnit()
   [string "*:OnEvent"]:1:
      [string "*:OnEvent"]:1
Locals:
name = nil
level = 0
unit = "mouseover"
isMob = false
(*temporary) = nil
(*temporary) = ":0"
(*temporary) = "0"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to concatenate local 'name' (a nil value)"
MI2_HideTimer = 0
MI2_UpdateGameTooltip = <function> defined @Interface\AddOns\MobInfo2\MI2_Tooltip.lua:294
MI2_CowFade = nil
MI2_StartTooltipMouseMove = <function> defined @Interface\AddOns\MobInfo2\MI2_Tooltip.lua:149
MI2_UpdateTooltip = <function> defined @Interface\AddOns\MobInfo2\MI2_Tooltip.lua:398

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.3.0
  ArkInventoryClassic, v10004
  ArkInventoryClassicRules, v10000
  ArkInventoryClassicRulesExample, v10000
  ArkInventoryClassicSearch, v10000
  AtlasLootClassic, vv1.1.8-beta
  AucAdvanced, v8.2.6385 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6368 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BeanCounter, v8.2.6381 (SwimmingSeadragon)
  BetterVendorPrice, vv1.04.00-classic
  ClassicAuraDurations, v
  DBMCore, v1.13.2
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Enchantrix, v8.2.6392 (SwimmingSeadragon)
  Informant, v8.2.6374 (SwimmingSeadragon)
  MobInfo2, v8.1.0
  OmniCC, v8.1.1
  Quartz, v3.5.1
  Questie, v4.0.10 BETA
  QuestXP, v0.2
  RecipeRadarClassic, v1.0.0.4
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TidyPlatesThreatPlates, v1.2.3
  TitanClassic, v1.0.5.11302
  TitanClassicAmmo, v1.0.5.11302
  TitanClassicBag, v1.0.5.11302
  TitanClassicClock, v1.0.5.11302
  TitanClassicGold, v1.0.5.11302
  TitanClassicLocation, v1.0.5.11302
  TitanClassicLootType, v1.0.5.11302
  TitanClassicPerformance, v1.0.5.11302
  TitanClassicRepair, v1.0.5.11302
  TitanClassicVolume, v1.0.5.11302
  TitanClassicXP, v1.0.5.11302
  WhatsTraining, v1.7
  YaHT, v
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=62e)

**Comment by ghost** [comment]
Hey, try using the newest version of MobInfo2-Classic :)
